
x 'ns_CloseFile.m'
'ns_GetAnalogData.m'
'ns_GetAnalogInfo.m'
'ns_GetEntityInfo.m'
'ns_GetEventData.m'
'ns_GetEventInfo.m'
'ns_GetFileInfo.m'
'ns_GetIndexByTime.m'
'ns_GetLastErrorMsg.m'
started 'ns_GetLibraryInfo.m'
'ns_GetNeuralData.m'
'ns_GetNeuralInfo.m'
'ns_GetSegmentData.m'
'ns_GetSegmentInfo.m'
'ns_GetSegmentSourceInfo.m'
'ns_GetTimeByIndex.m'
x 'ns_OpenFile.m'
'ns_SetLibrary.m'